.TH FB_REMOTE 1 2012-01-22 
.SH NAME 
\fBfb_remote\fR \(en t\('el\('ecommande Freebox en ligne de commande
.SH SYNOPSIS 
\fBfb_remote\fR touche[\fB+\fR] [\fBnombre de r\('ep\('etitions\fR]
.SH ENVIRONMENT
Il est n\('ecessaire d'initialiser la variable d'environnement \fIFREEBOX_TELECOMMAND_CODE\fR avec le code de la commande indiqu\('e dans l'\('ecran d'information de la Freebox.
.SH DESCRIPTION
Un nom de touche suivi de \fB+\fR indique un appui long.
.SS Touches disponibles
.IP \[bu] 
red
.IP \[bu]
green
.IP \[bu]
yellow
.IP \[bu]
blue
.IP \[bu]
power
.IP \[bu]
list
.IP \[bu]
tv
.IP \[bu]
0 \(`a 9
.IP \[bu]
back
.IP \[bu]
swap
.IP \[bu]
info, mail, help, pip
.IP \[bu]
epg, media, options
.IP \[bu]
vol_inc, vol_dec
.IP \[bu]
prgm_inc, prgm_dec
.IP \[bu]
ok
.IP \[bu]
up, right, down, left
.IP \[bu]
mute
.IP \[bu]
home
.IP \[bu]
rec
.IP \[bu]
bwd
.IP \[bu]
prev
.IP \[bu]
play
.IP \[bu]
fwd
.IP \[bu]
next
.SH AUTHORS
Ma\(:el Cl\('erambault <mael@clerambault.fr>
