#!/bin/sh

# Copyright (c) 2012 Mael Clerambault <mael@clerambault.fr>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

usage() {
  cat <<END
Usage: $0 touche[+] [nombre_de_repetition]

'+' dénote un appui long.

Noms des touches :
red
green
yellow
blue
power
list
tv
0 à 9
back
swap
info, mail, help, pip
epg, media, options
vol_inc, vol_dec
prgm_inc, prgm_dec
ok
up, right, down, left
mute
home
rec
bwd
prev
play
fwd
next
END
  exit 1
}

missing_code() {
  cat <<END
Vous devez initialiser le code de la freebox dans la variable
d'environnement FREEBOX_TELECOMMAND_CODE
END
  exit 1
}

[ $# -lt 1 ] && usage
[ -z "$FREEBOX_TELECOMMAND_CODE" ] && missing_code

key="${1%+}"
if [ "$key+" = "$1" ]; then
  long="&long=true"
fi
repeat=${2:-1}

curl "http://hd1.freebox.fr/pub/remote_control?key=$key&code=$FREEBOX_TELECOMMAND_CODE$long&repeat=$repeat"
