#!/bin/sh

CODE="__CODE_TELECOMMANDE__"

usage() {
  cat <<END
Usage: $0 touche[+] [nombre_de_repetition]

'+' dénote un appui long.

Noms des touches :
red
green
yellow
blue
power
list
tv
0 à 9
back
swap
info, mail, help, pip
epg, media, options
vol_inc, vol_dec
prgm_inc, prgm_dec
ok
up, right, down, left
mute
home
rec
bwd
prev
play
fwd
next
END
  exit 1
}

[ $# -lt 1 ] && usage

key="${1%+}"
if [ "$key+" = "$1" ]; then
  long="&long=true"
fi
repeat=${2:-1}

curl "http://hd1.freebox.fr/pub/remote_control?key=$key&code=$CODE$long&repeat=$repeat"
